version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1122331
      POSTGRES_DB: smart_campus_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net
    ports:
      - "5432:5432"

  # اختياري: تشغيل pgadmin لمراقبة القاعدة (تعطّله إن لم تحتاجه)
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - backend_net

volumes:
  db_data:

networks:
  backend_net:
    driver: bridge
